services:
  backend:
    build:
      context: ./backend
    container_name: manga_backend
    ports:
      - "8000:8000"
    shm_size: '2gb'
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - manga-network

  frontend:
    build:
      context: ./frontend
    container_name: manga_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - manga-network

  # --- AÑADIDO: TÚNEL AUTOMÁTICO ---
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: manga_tunnel
    # Conecta internamente al puerto 80 del frontend
    command: tunnel --url http://frontend:80
    networks:
      - manga-network
    depends_on:
      - frontend

networks:
  manga-network:
    driver: bridge
